sudo: required
dist: trusty
language: ruby
rvm:
  - 2.4.4
before_install:
  - gem update --system
  - gem install bundler
services:
  - postgresql
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - rm config/database.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test -c 'create extension hstore;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
